import { test, expect } from '@playwright/test';
const demoConfig = `export const config = { dataMode: 'demo', firebase: {} };`;

test('edita passageiro, converte em motorista e reverte preservando o cadastro', async ({ page }) => {
  await page.goto('./#passengers');
  await page.getByRole('textbox', { name: 'Buscar registros' }).fill('Beatriz');
  await page.getByRole('button', { name: 'Editar perfil' }).click();
  await page.getByLabel('Nome completo').fill('Beatriz Atualizada');
  await page.getByLabel('Cidade', { exact: true }).fill('Curuçá');
  await page.getByLabel('Tipo de usuário').selectOption('driver');
  await page.getByLabel('Modelo do veículo para novo motorista').fill('Fiat Uno');
  await page.getByRole('button', { name: 'Salvar usuário' }).click();
  await expect(page.locator('tbody')).toContainText('Motorista');
  await page.locator('nav').getByRole('button', { name: 'Motoristas', exact: true }).click();
  await page.getByRole('textbox', { name: 'Buscar registros' }).fill('Beatriz Atualizada');
  await expect(page.locator('.driver-card')).toHaveCount(1);
  await page.getByRole('button', { name: /Gerenciar/ }).click();
  await page.getByRole('button', { name: 'Editar usuário / converter em passageiro' }).click();
  await page.getByLabel('Tipo de usuário').selectOption('passenger');
  await page.getByRole('button', { name: 'Salvar usuário' }).click();
  await expect(page.locator('.driver-card')).toHaveCount(0);
  await page.reload();
  await page.locator('nav').getByRole('button', { name: 'Passageiros', exact: true }).click();
  await page.getByRole('textbox', { name: 'Buscar registros' }).fill('Beatriz Atualizada');
  await expect(page.locator('tbody')).toContainText('Passageiro');
  await expect(page.locator('tbody')).toContainText('Curuçá');
});
test.beforeEach(async ({ page }) => {
  await page.route('**/config.js', route => route.fulfill({ contentType: 'text/javascript', body: demoConfig }));
  await page.route('https://fonts.googleapis.com/**', route => route.abort());
});
test('publicação em subdiretório: navegação, filtro, formulário, persistência e CSV', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('./');
  await expect(page.getByRole('heading', { name: 'Sua operação, em movimento.' })).toBeVisible();
  await page.locator('nav').getByRole('button', { name: 'Motoristas' }).click();
  await page.getByRole('textbox', { name: 'Buscar registros' }).fill('Marina');
  await expect(page.locator('.driver-card')).toHaveCount(1);
  await page.getByRole('button', { name: 'Gerenciar' }).click();
  await page.getByLabel('Vagas disponíveis').fill('7');
  await page.getByRole('button', { name: 'Salvar alterações' }).click();
  await expect(page.getByRole('alert')).toContainText('excedem');
  await page.getByLabel('Vagas disponíveis').fill('2');
  await page.getByLabel('Preço (R$)').fill('17.50');
  await page.getByRole('button', { name: 'Salvar alterações' }).click();
  await expect(page.locator('dialog')).toHaveCount(0);
  await expect(page.locator('.driver-card')).toContainText('17,50');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Motoristas', exact: true })).toBeVisible();
  await expect(page.locator('.driver-card').first()).toContainText('2/6');
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Exportar relatório' }).click();
  expect((await download).suggestedFilename()).toContain('taxi-curuca-drivers-');
  expect(errors).toEqual([]);
});
test('aprovação cadastra motorista e atualiza passageiro; viagem e conversa preservadas', async ({ page }) => {
  await page.goto('./#applications');
  await page.getByRole('button', { name: 'Analisar', exact: true }).first().click();
  await page.getByRole('button', { name: 'Aprovar motorista' }).click();
  await expect(page.locator('tbody tr').first()).toContainText('Aprovado');
  await page.locator('nav').getByRole('button', { name: 'Motoristas' }).click();
  await expect(page.locator('.driver-card')).toHaveCount(6);
  await page.locator('nav').getByRole('button', { name: 'Viagens', exact: true }).click();
  await page.getByLabel('Filtrar registros').selectOption('in_progress');
  await page.getByRole('button', { name: 'Detalhes da viagem' }).first().click();
  await page.getByRole('button', { name: 'Concluir viagem' }).click();
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await page.locator('nav').getByRole('button', { name: 'Conversas' }).click();
  await page.locator('.chat-list button').click();
  await expect(page.locator('.message')).toHaveCount(3);
});
test('conteúdo de usuário é escapado e navegação móvel funciona', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('./#drivers');
  await page.getByRole('button', { name: 'Gerenciar' }).first().click();
  await page.getByLabel('Nome', { exact: true }).fill('<img src=x onerror=alert(1)>');
  await page.getByRole('button', { name: 'Salvar alterações' }).click();
  await expect(page.locator('.driver-card h3').first()).toHaveText('<img src=x onerror=alert(1)>');
  await expect(page.locator('.driver-card img')).toHaveCount(0);
  await page.getByRole('button', { name: 'Abrir menu' }).click();
  await page.locator('nav').getByRole('button', { name: 'Passageiros' }).click();
  await expect(page.getByRole('heading', { name: 'Passageiros', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('recusa exige motivo, persiste e não cadastra motorista', async ({ page }) => {
  await page.goto('./#applications');
  await page.getByRole('button', { name: 'Analisar', exact: true }).first().click();
  await page.getByRole('button', { name: 'Recusar cadastro' }).click();
  await expect(page.locator('dialog [role="alert"]')).toContainText('motivo');
  await page.getByLabel('Motivo da recusa').fill('Placa informada está incorreta');
  await page.getByRole('button', { name: 'Recusar cadastro' }).click();
  await expect(page.locator('tbody tr').first()).toContainText('Recusado');
  await page.reload();
  await page.getByRole('button', { name: 'Detalhes', exact: true }).first().click();
  await expect(page.locator('dialog')).toContainText('Placa informada está incorreta');
  await expect(page.getByRole('button', { name: 'Aprovar motorista' })).toHaveCount(0);
  await page.keyboard.press('Escape');
  await page.locator('nav').getByRole('button', { name: 'Motoristas' }).click();
  await expect(page.locator('.driver-card')).toHaveCount(5);
});
test('sem configuração mostra conexão pendente, nunca dados fictícios como reais', async ({ page }) => {
  await page.route('**/config.js', route => route.fulfill({ contentType: 'text/javascript', body: "export const config = { dataMode: 'firebase', firebase: {} };" }));
  await page.goto('./');
  await expect(page.getByRole('heading', { name: 'Acesse sua central' })).toBeVisible();
  await expect(page.locator('.settings-note')).toContainText('config.js');
  await expect(page.locator('.demo-banner')).toHaveCount(0);
});
test('login, eventos de dados em tempo real e saída limpam a sessão', async ({ page }) => {
  await page.route('**/config.js', route => route.fulfill({ contentType: 'text/javascript', body: `export const config = { dataMode: 'firebase', firebase: { apiKey: 'test', authDomain: 'test', projectId: 'test' } };` }));
  await page.route('**/src/firebase.js', route => route.fulfill({ contentType: 'text/javascript', body: `
    import { seedData } from './data.js';
    let session; const user = { uid: 'admin', email: 'admin@example.com' };
    export const watchSession = callback => { session = callback; callback(null); };
    export const requireAdmin = async () => user;
    export const ensureAdminProfile = async () => {};
    export const watchAdminAccess = callback => { callback(true); return () => {}; };
    export const login = async () => session(user);
    export const logout = async () => session(null);
    export const resetPassword = async email => { window.resetEmail = email; };
    export const subscribeData = (callback) => { const data = seedData(); queueMicrotask(() => callback(data)); window.updateTestData = () => { data.users.push({id:'live', fullName:'Passageiro ao vivo'}); callback({...data}); }; return () => {}; };
  ` }));
  await page.goto('./');
  await page.getByLabel('E-mail').fill('admin@example.com');
  await page.getByLabel('Senha').fill('password');
  await page.getByRole('button', { name: 'Mostrar senha' }).click();
  await expect(page.getByLabel('Senha', { exact: true })).toHaveAttribute('type', 'text');
  await page.getByRole('button', { name: 'Ocultar senha' }).click();
  await page.getByRole('button', { name: 'Esqueci minha senha' }).click();
  await page.getByRole('button', { name: 'Enviar link de recuperação' }).click();
  expect(await page.evaluate(() => window.resetEmail)).toBe('admin@example.com');
  await page.getByRole('button', { name: 'Entrar no painel' }).click();
  await expect(page.locator('.metrics')).toBeVisible();
  await page.evaluate(() => window.updateTestData());
  await page.locator('nav').getByRole('button', { name: 'Passageiros' }).click();
  await expect(page.locator('tbody')).toContainText('Passageiro ao vivo');
  await page.getByRole('button', { name: 'Configurações', exact: true }).click();
  await page.getByRole('button', { name: 'Sair da conta' }).click();
  await expect(page.getByRole('heading', { name: 'Acesse sua central' })).toBeVisible();
  await expect(page.locator('table')).toHaveCount(0);
});
test('administradores: criar, editar, desativar, persistir e proteger a própria conta', async ({ page }) => {
  await page.goto('./#admins');
  await expect(page.getByRole('heading', { name: 'Administradores', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Novo administrador', exact: true }).click();
  await page.getByLabel('Nome', { exact: true }).fill('Maria Admin');
  await page.getByLabel('E-mail de acesso').fill('maria@example.com');
  await page.getByLabel('Senha inicial').fill('MinhaSenha123');
  await page.getByRole('button', { name: 'Criar administrador' }).click();
  const row = page.locator('tbody tr').filter({ hasText: 'maria@example.com' });
  await expect(row).toContainText('Ativo');
  expect(await page.evaluate(() => localStorage.getItem('taxi-curuca-demo-v1'))).not.toContain('MinhaSenha123');
  await row.getByRole('button', { name: 'Editar' }).click();
  await expect(page.getByLabel('E-mail de acesso')).toHaveAttribute('readonly', '');
  await page.getByLabel('Nome', { exact: true }).fill('Maria Silva');
  await page.getByLabel('Acesso administrativo ativo').uncheck();
  await page.getByRole('button', { name: 'Salvar administrador' }).click();
  await page.reload();
  await expect(row).toContainText('Maria Silva');
  await expect(row).toContainText('Desativado');
  await page.locator('tbody tr').filter({ hasText: '(você)' }).getByRole('button', { name: 'Editar' }).click();
  await expect(page.getByLabel('Acesso administrativo ativo')).toBeDisabled();
});
